### ISSUE TITLE
Edición del registro

### ISSUE THREAD

**Issue by ivanprietouvigo** [observesport/lince-plus#10]
Sería interesante que se pudieran editar las categorías marcadas en el registro. Esta función estaba en el LINCE 1, en donde si tú te equivocabas en la categoría del criterio que has previamente registrado, luego se pudieras editar en la propia casilla del registro sin tener que borrarla y volver a registrarla, haciendo doble clic en la categoría donde te equivocaste.

**Comment by albertoSoto** [comment]
Buenos días Ivan,

Ahora, al seleccionar el registro durante unos segundos se marca en naranja.
Si es así, la edición se realiza sobre el registro marcado.

![image](https://user-images.githubusercontent.com/3663174/143024758-9584d018-1ada-41e0-8c2f-2158d5f4f90f.png)
