### ISSUE TITLE
Atajos de teclado en el registro.

### ISSUE THREAD

**Issue by ivanprietouvigo** [observesport/lince-plus#11]
Los atajos de teclado en el apartado de registro funcionan para la reproducción del vídeo, pero no para registrar. Esta mejora podría ayudar a mejorar la velocidad en el registro. Desde mi punto de vista, yo usaría la tecla Q para play/pausa (sin distinción con otra tecla -es más cómodo que no sean dos-) y la tecla R (de registro) o la de barra espaciadora (tecla bastante amplia) para añadir lo marcado en el registro (por ejemplo), manteniendo el resto de atajos tal y como están. Cuando se registra, es muy cómodo con la mano hábil marcar el botón y no la no hábil (mayoritariamente la izquierda) ir haciendo play/pausa y registrando.  Creo que la opción Q y R o Q y Espacio serían bastante óptimas (por la distancia entre los dedos y su colocación en el teclado) para realizar esta tarea.

**Comment by albertoSoto** [comment]
Buenos días Ivan, esta opción ya está solucionada.
He incluido las acciones en el el botón superior de vídeo

![image](https://user-images.githubusercontent.com/3663174/143024501-0e697cd7-b4f9-40e1-a0cd-fdfce1c2b503.png)
