### ISSUE TITLE
Reemplazo de una categoría que ya fue registrada

### ISSUE THREAD

**Issue by ivanprietouvigo** [observesport/lince-plus#12]
Sería interesante que, si tú cambias el nombre de la categoría en el instrumento, se cambiara automáticamente en el registro (se podía hacer en Lince v1), que hubiera una función de reemplazo.

**Comment by albertoSoto** [comment]
Buenos días Ivan!!!
Este es un problema muy grande y no tiene solución.
Si cambias el nombre, se actualiza sin problemas, pero no es así con el código.
El problema es que nunca puedo saber si el código es nuevo, es un reemplazo o proviene de otra categoría.

Lo único que podemos hacer es dejar la edición libre y advertir de que no se modifique.

La otra opción sería borrar todos los registros que usan el código que no existe, pero no tengo forma de saber si quieres que lo borre, si quieres que lo actualice...es muy muy complicado.

Cierro la petición por no tener solución
