### ISSUE TITLE
Escenas con puntos rojos que existían anteriormente

### ISSUE THREAD

**Issue by ocamerino** [observesport/lince-plus#17]
En la primera versión aparecia en la opción de escenas debajo de la filmación unos puntos rojos pertenecientes a las escenas. Creo que se tendría que recuperar.
Gracias

**Comment by albertoSoto** [comment]
Esta peticion requiere modificar el visor de video, queda postpuesta a v3.0

**Comment by albertoSoto** [comment]
Published on 2.1
