### ISSUE TITLE
 guardar episodios con una tecla rápidamente y así simplificar el movimiento del ratón

### ISSUE THREAD

**Issue by JulCasPau** [observesport/lince-plus#23]
Hola,
Estoy pensando en agilizar el proceso de registro, esto pasa por reducir el numero de ckick a realizar a medida que la herramienta de codificación lo permita. La opción que comentas de agilizar el 'save' con alguna tecla esta bien, incluso que los propios códigos tuvieran la opción de tecla también. En segun que contextos y herramientas de codificación (HC) creo que podría ayudar mucho. 
La otra opción que planteo es la de conectar categorias que se hagan excluyentes. Claro!, son con HC sencillas. básicamente con tipo de dato secuencias de evento o secuencias de estado. Esto implica que activar un código es generar una escena (creo que le llamas) y al activar otra se desactiva la anterior.
A ver si te sirve, cualuier cosa me dices.

**Comment by albertoSoto** [comment]
Shortcut working for "G" key
Will add the map to key
Will need a custom dashboard to replace or personalize it, but complexity for that can have side effects
