### ISSUE TITLE
Acceso directo a generar una sugerencia para LINCE

### ISSUE THREAD

**Issue by ivanprietouvigo** [observesport/lince-plus#50]
Para que los usuarios pudieran reportar errores más fácilmente, creo que se podría poner un acceso directo a https://github.com/observesport/lince-plus/issues en la pestaña de Ayuda que tiene el LINCE cuando se inicia.

**Comment by albertoSoto** [comment]
La nueva version 2.1 introduce manejo de video con teclado y un sistema de mensajes automatico.
Informaremos en poco de las mejoras
