### ISSUE TITLE
Fallo en la exportación a Excel (problema grave)

### ISSUE THREAD

**Issue by ivanprietouvigo** [observesport/lince-plus#58]
He comprobado que LINCE plus 2.1 realiza varios errores en las exportación de archivos a Excel y Theme. Por un lado, a veces hay que cerrar LINCE y volver a abrirlo para que cuando haces clic en exportar se pueda ejecutar la acción. Pero, lo más importante es que, cuando se hace la exportación, lo frames no coinciden (en lince aparecen unos frames y tiempos asociados a la categoría registrada y en excel otros totalmente diferentes). Esto es un grave problema por dos razones al menos: una, los estudios temporales no se pueden realizar y dos, si hay algún error en el registro que has visualizado en Excel, no puedes saber donde está, ya que el frame no coincide. En exportación a Theme sucede exactamente lo mismo. 

![image](https://github.com/observesport/lince-plus/assets/72381539/f8c7b980-979c-4387-a8c4-fcccef6d608e)

**Comment by albertoSoto** [comment]
Buenas @ivanprietouvigo !!!

Por fin hemos conseguido solucionar esto. Estara en la version 3.2.2

**Comment by ivanprietouvigo** [comment]
Muchas gracias Alberto!
Me alegra saber que ese fallo se ha corregido. 
Un abrazo.
